### ISSUE TITLE
Erro com alguns estados

### ISSUE THREAD

**Issue by rafaelsabino** [hitalos/covid19#1]
Parceiro, gostei muito da sua iniciativa só que está dando erro para buscar os dados de MT, DF, e alguns outros estados. Simplesmente não lê os dados da função. O mapa global é exibido normalmente, porém quando você filtra alguns estados dá erro. MG, SP está ótimo, porém alguns outros não exibem e recebo o seguinte erro: 

Diz que não consegue preparar os dados para alguns estados. Sabe o motivo?

estados.js:26 Uncaught (in promise) TypeError: Cannot read property 'confirmed' of undefined
    at prepareData (estados.js:26)
    at estados.js:57

**Comment by hitalos** [comment]
Opa! Você executou o script que baixa os arquivos CSV pra cada estado? Algum erro na saída destes? Caso não, veja como está o conteúdo dos arquivos, se há alguma diferença entre os que estão com erro e os que estão exibindo corretamente.

**Comment by rafaelsabino** [comment]
Sim, consegui baixar todos os .csv em cada pasta, porém não consegui fazer com que alguns estados sejam exibidos. Pra você os estados que citei com problemas são mostrados? Pois pra mim aparece erro na função.

**Comment by hitalos** [comment]
Tô vendo aqui o erro. Ontem dei uma simplificada nos scripts. Pode ter sido alguma coisa que mudei. Acho que ainda hoje consigo resolver.

**Comment by hitalos** [comment]
Vê lá, acho que agora tá resolvido.

**Comment by rafaelsabino** [comment]
Perfeito Hitalo, agora sim apareceu todos os mapas. Cara você é fera. Valeu!
