### ISSUE TITLE
Dados Globais

### ISSUE THREAD

**Issue by rafaelsabino** [hitalos/covid19#2]
Hitalo, bom dia, tudo bem? 

Cara não encontrei seu e-mail aqui então vou falar por aqui mesmo. 

parceiro eu estava precisando capturar os dados globais de todos os paises e transformar em um array no php ou no javascript para poder criar gráficos em fusioncharts. 

Quanto você cobraria só pra me fazer essa função? 

já rodei a internet inteira e não achei, você parece entender muito bem disso. 

Hoje tenho aqui timeseries em json e csv, que são atualizados em tempo real, mas não to sabendo passar direto pra um array pra puxar no gráfico. 

Seria mais ou menos isso: 

-Link do json online;
-Capturar os dados;
-Transformar em um array php parecido com essa ordem aqui:
```
[
"13/04/2020",
1560,
35,
128],
[
"12/04/2020",
1560,
35,
128],.......
```
Assim eu consigo criar os gráficos. Porém tentei de todas as formas agrupar os json ou csv e sempre com erros. 
Você consegue fazer isso? caso sim qnto cobraria?

**Comment by rafaelsabino** [comment]
Pode deixar Hitalo, vou dar um jeito aqui com os csv's mesmo. Não vou incomodar não kk. Valeu.

**Comment by hitalos** [comment]
Oi cara, desculpa a demora. Muita coisa aqui entre trabalho e esse projeto pessoal.
Tô bem enferrujado de PHP. A lib que usei no projeto é em JS, segue abaixo o link da documentação. Veja as funções `d3.json` e `d3.csv`.

https://github.com/d3/d3/wiki
